### ISSUE TITLE
LateUpdate() issue

### ISSUE THREAD

**Issue by usman98789** [sagering/UnityNetcodeSteamP2PRelayTransport#1]
Hey! I found your transport to be really useful to attach to the NGO's Network Manager to use Steams Datagram Relay.

I got the joining lobby set up and am able to join my lobby using Facepunch for steam API calls and your script as a transport.

I have a main menu script that contains a button to leave the lobby. 

    public void OnClickLeaveLobby()
    {

        if(NetworkManager.Singleton.IsServer)
        {
            NetworkManager.Singleton.Shutdown();
        }
        else
        {
            NetworkManager.DisconnectClient(networkClient.PlayerObject.OwnerClientId);
        }
    }

When I leave the lobby the socketManager which is defined (in your StartServer method) 
goes null and throws "NullReferenceException: Object reference not set to an instance of an object" on the line of socket.recieve in the LateUpdate() from your script

    void LateUpdate()
    {
        socketManager?.Receive();
        clientConnection?.Receive();
    }

Any ideas why this may be happening?

**Comment by sagering** [comment]
Can you check if you are entering the "Shutdown" method in SteamP2PRelayTransport.cs

```
override public void Shutdown()
{
    Debug.Log("Shutdown.");
    Steamworks.SteamClient.Shutdown();
}
```

My quess is that we should not actuallly call `Steamworks.SteamClient.Shutdown()` in the transport shutdown. Can you try to comment out this part and see if you still get the exception?
